# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn

      - name: Setup VPN config
        run: |
          echo """${{ secrets.STAGING_CONFIG }}""" > config.ovpn
          echo "${{ secrets.USER_NAME }}" > secret.ovpn
          echo "${{ secrets.USER_PW }}" >> secret.ovpn

      - name: Connect VPN
        run: sudo openvpn --config config.ovpn --auth-user-pass secret.ovpn --log "vpn.log" --daemon

      - name: Deploy to CN Staging server
        uses: appleboy/ssh-action@v0.1.6
        if: github.ref == 'refs/heads/development'
        with:
          password: ${{ secrets.SSH_PW }}
          host: 192.168.20.70
          username: 'cn'
        script: |
          cd website
          whoami
          ls -al
